---
- name: Playbook to install apache on RHEL family servers
  hosts: all
  become: true

  tasks:
  - name: Installing httpd
    yum:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"
    notify: Starting httpd

  - name: Installing apache
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: Starting apache2

  - name: Copy index.html to target servers
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666

  handlers:
  - name: Starting apache2
    systemd:
      name: apache2
      state: started

  
  - name: Starting httpd
    systemd:
      name: httpd
      state: started

