---
- name: Install several packages
  hosts: webservers
  become: true
  
  tasks:
  - name: Installing packages
    yum:
      name:
        - "git"
        - "make"
        - "gzip"
        - "tree"
        - "wget"
        - "telnet"
      state: present

