---
- name: Setup Tomcat
  hosts: all
  become: true

  tasks:
  - name: Install Java (RedHat)
    yum:
      name: java:
      state: present
    when: ansible_os_family == "RedHat"

  - name: Install Java (Ubuntu)
    apt:
      name: default-jdk
      state: installed
    when: ansible_os_family == "Debian"

  - name: Download Tomcat sources
    get_url:
      url: https://mirror.jframeworks.com/apache/tomcat/tomcat-8/v8.5.61/bin/apache-tomcat-8.5.61.tar.gz
      dest: /opt/downloads
    
  - name: Extract Tomcat
    unarchive:
      scr: /opt/download/apache-tomcat-8.5.61.tar.gz
      dest: /opt/tomcat/
      remote_src: yes

  - name: Make start.sh executable
    file:
      path: /opt/tomcat/bin/startup.sh
      mode: u+x
  
  - name: Start tomcat server
    shell: ./startup.sh
    args:
      chdir: /opt/tomcat/bin/
