---
- name: Installing httpd
  yum:
    name: httpd
    state: latest
  when: ansible_os_family == "RedHat"
  tags: install_httpd

- name: Change http default port to {{ custom_port }} in RedHat
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "^Listen"
    line: "Listen {{ custom_port  }}"
  when: ansible_os_family == "RedHat"
